version: '3.8'

services: 
    web:
        build: .
        command: python ./app/manage.py run -h 0.0.0.0
        volumes:
            - .:/app
        expose: 
            - 5000
        env_file:
            - .env.dev
        depends_on: 
            - db
        labels: 
            - "traefik.enable=true"
            - "traefik.http.routers.flask.rule=Host(`flask.localhost`)"

    db:
        image: postgres:13-alpine
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        expose: 
            - 5432
        environment: 
            - POSTGRES_USER=hello_flask
            - POSTGRES_PASSWORD=hello_flask
            - POSTGRES_DB=hello_flask_dev
    treafik:
        image: traefik:v2.2
        ports:
            - 80:80
            - 8081:8080
        volumes:
            - "./traefik.dev.toml:/etc/traefik/traefik.toml"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes: 
    postgres_data: